package com.cafeapp.views;

/**
 *
 * @author Pranav Sharma LMU ID:23048577
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblforhomebackground = new javax.swing.JLabel();
        pnlforMenubar = new javax.swing.JPanel();
        btnfordashboard1 = new javax.swing.JButton();
        btnforadd1 = new javax.swing.JButton();
        lblforsettings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        lblforhomebackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homepanel.jpg"))); // NOI18N

        pnlforMenubar.setBackground(new java.awt.Color(240, 232, 219));
        pnlforMenubar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 79, 38)));

        btnfordashboard1.setBackground(new java.awt.Color(240, 232, 219));
        btnfordashboard1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnfordashboard1.setForeground(new java.awt.Color(145, 79, 38));
        btnfordashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btnfordashboard1.setText("DASHBOARD");
        btnfordashboard1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(145, 79, 38), 2, true));
        btnfordashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfordashboard1ActionPerformed(evt);
            }
        });

        btnforadd1.setBackground(new java.awt.Color(240, 232, 219));
        btnforadd1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnforadd1.setForeground(new java.awt.Color(145, 79, 38));
        btnforadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnforadd1.setText("ADD ITEMS");
        btnforadd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 79, 38), 2));
        btnforadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforadd1ActionPerformed(evt);
            }
        });

        lblforsettings.setBackground(new java.awt.Color(240, 232, 219));
        lblforsettings.setForeground(new java.awt.Color(240, 232, 219));
        lblforsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—settings icon_4491632.png"))); // NOI18N
        lblforsettings.setText("jLabel1");

        javax.swing.GroupLayout pnlforMenubarLayout = new javax.swing.GroupLayout(pnlforMenubar);
        pnlforMenubar.setLayout(pnlforMenubarLayout);
        pnlforMenubarLayout.setHorizontalGroup(
            pnlforMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlforMenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlforMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnforadd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfordashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlforMenubarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblforsettings, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlforMenubarLayout.setVerticalGroup(
            pnlforMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlforMenubarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblforsettings, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnfordashboard1)
                .addGap(40, 40, 40)
                .addComponent(btnforadd1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlforMenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblforhomebackground))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblforhomebackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlforMenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// This method is used to go to dashboard
    private void btnfordashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfordashboard1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnfordashboard1ActionPerformed

//This method is used to go to the Add form from Home page
    private void btnforadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforadd1ActionPerformed
        setVisible(false);
        new Add().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnforadd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnforadd1;
    private javax.swing.JButton btnfordashboard1;
    private javax.swing.JLabel lblforhomebackground;
    private javax.swing.JLabel lblforsettings;
    private javax.swing.JPanel pnlforMenubar;
    // End of variables declaration//GEN-END:variables
}
